on:
  schedule:
    - cron: '0 0 * * *'
name: Auto-update
jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Update upstream code
        run: |
          git -C yosys-src pull --ff-only origin master
          git -C SymbiYosys-src pull --ff-only origin master
      - name: Push updated code
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update dependencies.
